.DEFAULT_GOAL := build

fmt:
	go fmt ./...
lint: fmt
	golint ./...
vet: fmt
	go vet ./...
test: vet
	gotestsum --format pkgname --junitfile report.xml -- -failfast -race -coverprofile=coverage.out ./...
build: test
	go build -o main/app ./main/main.go